image: php:7.1.1

pipelines:
  default:
    - step:
        caches:
          - composer
        artifacts:
          - vendor/**
        script:
          - apt-get update && apt-get install -y unzip
          - apt-get install -y git
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpunit --bootstrap vendor/autoload.php tests